"""add clob_token_ids and event_slug to markets

Revision ID: 1c4c9e758481
Revises: 515b9ced7c47
Create Date: 2026-05-29 15:34:03.468645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c4c9e758481'
down_revision: Union[str, Sequence[str], None] = '515b9ced7c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('clob_token_ids', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('markets', sa.Column('event_slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'event_slug')
    op.drop_column('markets', 'clob_token_ids')
    # ### end Alembic commands ###
